name: 部署到github pages

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置node环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: 安装依赖
        run: pnpm install

      - name: 构建
        run: pnpm run build-pc

      - name: 部署到github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/pc/dist